/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import main.Shop;
import model.Files;
import model.Product;

/**
 *
 * @author admin
 */
public class ProductView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductView.class.getName());
    private final Shop shop;
    private final int opc;

    /**
     * Creates new form ProductView
     */
    public ProductView(java.awt.Frame parent, boolean modal, Shop shop, int opc) {
        super(parent, modal);
        initComponents();
        this.shop = shop;
        this.opc = opc;
        setTitle("Menú de Product");
        setLocationRelativeTo(null);
        setResizable(false);

        if (9 == opc) {
            labelProductStock.setEnabled(false);
            productStock.setEnabled(false);
            labelPriceProduct.setEnabled(false);
            priceProduct.setEnabled(false);
        } else if (3 == opc) {
            labelPriceProduct.setEnabled(false);
            priceProduct.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProductName = new javax.swing.JLabel();
        labelProductStock = new javax.swing.JLabel();
        labelPriceProduct = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        productName = new javax.swing.JTextField();
        productStock = new javax.swing.JTextField();
        priceProduct = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelProductName.setText("Nombre producto:");

        labelProductStock.setText("Stock producto:");

        labelPriceProduct.setText("Precio producto:");

        ok.setText("OK");
        ok.addActionListener(this::okActionPerformed);

        cancel.setText("Cancel");
        cancel.addActionListener(this::cancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(202, Short.MAX_VALUE)
                        .addComponent(cancel)
                        .addGap(18, 18, 18)
                        .addComponent(ok))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProductName)
                            .addComponent(labelProductStock)
                            .addComponent(labelPriceProduct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productName)
                            .addComponent(productStock)
                            .addComponent(priceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProductName)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProductStock)
                    .addComponent(productStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPriceProduct)
                    .addComponent(priceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        String pName = productName.getText().trim();
        String pPrice = priceProduct.getText();

        switch (opc) {
            case 2:
                if (shop.findProduct(pName) != null) {
                    JOptionPane.showMessageDialog(this, "Añadir producto incorrecto", "Este producto YA existe", JOptionPane.ERROR_MESSAGE);
                } else {
                    shop.addProduct(new Product(pName));
                    JOptionPane.showMessageDialog(this, "Añadir producto correcto", "Se ha añadido el producto con éxito", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
                break;
            case 3:
                int pStock = Integer.parseInt(productStock.getText());
                
                if (shop.findProduct(pName) != null) {
                    shop.addStock(pName, pStock);
                    JOptionPane.showMessageDialog(this, "Añadir stock correcto", "Se ha añadido el stock con éxito", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Añadir stock incorrecto", "Este producto NO existe", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case 9:
                if (shop.findProduct(pName) != null) {
                    shop.deleteProduct(pName);
                    JOptionPane.showMessageDialog(this, "Eliminar producto correcto", "Se ha eliminado el producto con éxito", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Eliminar producto incorrecto", "Este producto NO existe", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel labelPriceProduct;
    private javax.swing.JLabel labelProductName;
    private javax.swing.JLabel labelProductStock;
    private javax.swing.JButton ok;
    private javax.swing.JTextField priceProduct;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productStock;
    // End of variables declaration//GEN-END:variables
}
