/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import main.Shop;
import model.Files;

/**
 *
 * @author admin
 */
public class ShopView extends javax.swing.JFrame {

    Shop shop;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopView.class.getName());

    /**
     * Creates new form ShopView
     */
    public ShopView() {
        initComponents();
        this.shop = new Shop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add_stock = new javax.swing.JButton();
        cash_up = new javax.swing.JButton();
        add_product = new javax.swing.JButton();
        delete_product = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione o pulse una opcion:");

        add_stock.setText("AÑADIR STOCK");
        add_stock.addActionListener(this::add_stockActionPerformed);

        cash_up.setText("CONTAR CAJA");
        cash_up.addActionListener(this::cash_upActionPerformed);
        cash_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cash_upKeyPressed(evt);
            }
        });

        add_product.setText("AÑADIR PRODUCTO");
        add_product.addActionListener(this::add_productActionPerformed);

        delete_product.setText("ELIMINAR PRODUCTO");
        delete_product.addActionListener(this::delete_productActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete_product, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cash_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(cash_up)
                .addGap(18, 18, 18)
                .addComponent(add_product)
                .addGap(18, 18, 18)
                .addComponent(add_stock)
                .addGap(18, 18, 18)
                .addComponent(delete_product)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_productActionPerformed
        // TODO add your handling code here:
        //        ProductView productView = new ProductView(this, true, shop);
        //        productView.setLocationRelativeTo(this);
        //        productView.setVisible(true);
        int add = 9;
        openProductView(add);
    }//GEN-LAST:event_delete_productActionPerformed

    private void add_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stockActionPerformed
        // TODO add your handling code here:
        //        ProductView productView = new ProductView(this, true, shop);
        //        productView.setLocationRelativeTo(this);
        //        productView.setVisible(true);
        int add = 3;
        openProductView(add);

    }//GEN-LAST:event_add_stockActionPerformed

    private void add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_productActionPerformed
        // TODO add your handling code here:
        //        ProductView productView = new ProductView(this, true, shop);
        //        productView.setLocationRelativeTo(this);
        //        productView.setVisible(true);
        int add = 2;
        openProductView(add);
    }//GEN-LAST:event_add_productActionPerformed

    private void cash_upKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cash_upKeyPressed

    }//GEN-LAST:event_cash_upKeyPressed

    private void cash_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_upActionPerformed
        // TODO add your handling code here:
        CashView cashView = new CashView(this, true, shop);
        cashView.setLocationRelativeTo(this);
        cashView.setVisible(true);
    }//GEN-LAST:event_cash_upActionPerformed

    private void openProductView(int opc) {
        ProductView productView = new ProductView(this, true, shop, opc);
        productView.setLocationRelativeTo(this);
        productView.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product;
    private javax.swing.JButton add_stock;
    private javax.swing.JButton cash_up;
    private javax.swing.JButton delete_product;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
