/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import main.Shop;

/**
 *
 * @author admin
 */
public class ShopView extends javax.swing.JFrame {
    Shop shop;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopView.class.getName());

    /**
     * Creates new form ShopView
     */
    public ShopView() {
        initComponents();
        this.shop = new Shop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cash_up = new javax.swing.JButton();
        add_stock = new javax.swing.JButton();
        delete_product = new javax.swing.JButton();
        add_product = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cash_up.setText("CONTAR CAJA");
        cash_up.addActionListener(this::cash_upActionPerformed);
        cash_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cash_upKeyPressed(evt);
            }
        });

        add_stock.setText("AÑADIR STOCK");
        add_stock.addActionListener(this::add_stockActionPerformed);

        delete_product.setText("ELIMINAR PRODUCTO");
        delete_product.addActionListener(this::delete_productActionPerformed);

        add_product.setText("AÑADIR PRODUCTO");
        add_product.addActionListener(this::add_productActionPerformed);

        jLabel1.setText("Seleccione o pulse una opcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delete_product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cash_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_product, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(cash_up)
                .addGap(18, 18, 18)
                .addComponent(add_product)
                .addGap(18, 18, 18)
                .addComponent(add_stock)
                .addGap(18, 18, 18)
                .addComponent(delete_product)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cash_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_upActionPerformed
        // TODO add your handling code here:
        CashView cashView = new CashView(this, true, shop);
        cashView.setLocationRelativeTo(this);
        cashView.setVisible(true);
    }//GEN-LAST:event_cash_upActionPerformed

    private void add_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_stockActionPerformed

    private void delete_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_productActionPerformed

    private void add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_productActionPerformed

    private void cash_upKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cash_upKeyPressed
        if (evt.getKeyChar() == '1') {
            CashView cashView = new CashView(this, true, shop);
            cashView.setLocationRelativeTo(this);
            cashView.setVisible(true);
        }
    }//GEN-LAST:event_cash_upKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShopView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product;
    private javax.swing.JButton add_stock;
    private javax.swing.JButton cash_up;
    private javax.swing.JButton delete_product;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
